spring:
    application:
        name: jspweb
    profiles:
        active: dev

    # HTTP ENCODING
    http:
        encoding.charset: UTF-8
        encoding.enable: true
        encoding.force: true

    #jsp
    mvc:
      view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp

server:
  port: 8080

  #for error page
  error:
    whitelabel:
      enabled: false

logging:
    level:
        com.dzr.web: debug
    file: /home/wwwlogs/${spring.application.name}.log